// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../interfaces/interfaces.go -destination=../tests/mock_interfaces.go -package=tests
//

// Package tests is a generated GoMock package.
package tests

import (
	models "cloud-clips/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageInterface is a mock of StorageInterface interface.
type MockStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockStorageInterfaceMockRecorder is the mock recorder for MockStorageInterface.
type MockStorageInterfaceMockRecorder struct {
	mock *MockStorageInterface
}

// NewMockStorageInterface creates a new mock instance.
func NewMockStorageInterface(ctrl *gomock.Controller) *MockStorageInterface {
	mock := &MockStorageInterface{ctrl: ctrl}
	mock.recorder = &MockStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInterface) EXPECT() *MockStorageInterfaceMockRecorder {
	return m.recorder
}

// CreateAppointment mocks base method.
func (m *MockStorageInterface) CreateAppointment(appointment *models.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppointment", appointment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAppointment indicates an expected call of CreateAppointment.
func (mr *MockStorageInterfaceMockRecorder) CreateAppointment(appointment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppointment", reflect.TypeOf((*MockStorageInterface)(nil).CreateAppointment), appointment)
}

// CreateBarberProfile mocks base method.
func (m *MockStorageInterface) CreateBarberProfile(profile *models.BarberProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBarberProfile", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBarberProfile indicates an expected call of CreateBarberProfile.
func (mr *MockStorageInterfaceMockRecorder) CreateBarberProfile(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBarberProfile", reflect.TypeOf((*MockStorageInterface)(nil).CreateBarberProfile), profile)
}

// CreateUser mocks base method.
func (m *MockStorageInterface) CreateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageInterfaceMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorageInterface)(nil).CreateUser), user)
}

// DeleteAppointment mocks base method.
func (m *MockStorageInterface) DeleteAppointment(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppointment", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppointment indicates an expected call of DeleteAppointment.
func (mr *MockStorageInterfaceMockRecorder) DeleteAppointment(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppointment", reflect.TypeOf((*MockStorageInterface)(nil).DeleteAppointment), id)
}

// DeleteBarberProfile mocks base method.
func (m *MockStorageInterface) DeleteBarberProfile(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBarberProfile", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBarberProfile indicates an expected call of DeleteBarberProfile.
func (mr *MockStorageInterfaceMockRecorder) DeleteBarberProfile(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBarberProfile", reflect.TypeOf((*MockStorageInterface)(nil).DeleteBarberProfile), id)
}

// DeleteUser mocks base method.
func (m *MockStorageInterface) DeleteUser(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStorageInterfaceMockRecorder) DeleteUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStorageInterface)(nil).DeleteUser), id)
}

// GetAppointment mocks base method.
func (m *MockStorageInterface) GetAppointment(id uuid.UUID) (*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointment", id)
	ret0, _ := ret[0].(*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointment indicates an expected call of GetAppointment.
func (mr *MockStorageInterfaceMockRecorder) GetAppointment(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointment", reflect.TypeOf((*MockStorageInterface)(nil).GetAppointment), id)
}

// GetAppointments mocks base method.
func (m *MockStorageInterface) GetAppointments() ([]*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppointments")
	ret0, _ := ret[0].([]*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppointments indicates an expected call of GetAppointments.
func (mr *MockStorageInterfaceMockRecorder) GetAppointments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppointments", reflect.TypeOf((*MockStorageInterface)(nil).GetAppointments))
}

// GetBarberAppointments mocks base method.
func (m *MockStorageInterface) GetBarberAppointments(barberID uuid.UUID) ([]*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarberAppointments", barberID)
	ret0, _ := ret[0].([]*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarberAppointments indicates an expected call of GetBarberAppointments.
func (mr *MockStorageInterfaceMockRecorder) GetBarberAppointments(barberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarberAppointments", reflect.TypeOf((*MockStorageInterface)(nil).GetBarberAppointments), barberID)
}

// GetBarberProfile mocks base method.
func (m *MockStorageInterface) GetBarberProfile(id uuid.UUID) (*models.BarberProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarberProfile", id)
	ret0, _ := ret[0].(*models.BarberProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarberProfile indicates an expected call of GetBarberProfile.
func (mr *MockStorageInterfaceMockRecorder) GetBarberProfile(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarberProfile", reflect.TypeOf((*MockStorageInterface)(nil).GetBarberProfile), id)
}

// GetBarberProfiles mocks base method.
func (m *MockStorageInterface) GetBarberProfiles() ([]*models.BarberProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarberProfiles")
	ret0, _ := ret[0].([]*models.BarberProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarberProfiles indicates an expected call of GetBarberProfiles.
func (mr *MockStorageInterfaceMockRecorder) GetBarberProfiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarberProfiles", reflect.TypeOf((*MockStorageInterface)(nil).GetBarberProfiles))
}

// GetUser mocks base method.
func (m *MockStorageInterface) GetUser(id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStorageInterfaceMockRecorder) GetUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStorageInterface)(nil).GetUser), id)
}

// GetUserAppointments mocks base method.
func (m *MockStorageInterface) GetUserAppointments(userID uuid.UUID) ([]*models.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAppointments", userID)
	ret0, _ := ret[0].([]*models.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAppointments indicates an expected call of GetUserAppointments.
func (mr *MockStorageInterfaceMockRecorder) GetUserAppointments(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAppointments", reflect.TypeOf((*MockStorageInterface)(nil).GetUserAppointments), userID)
}

// GetUsers mocks base method.
func (m *MockStorageInterface) GetUsers() ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers")
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockStorageInterfaceMockRecorder) GetUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockStorageInterface)(nil).GetUsers))
}

// SearchBarbers mocks base method.
func (m *MockStorageInterface) SearchBarbers(lat, lng, radius float64) ([]*models.BarberProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBarbers", lat, lng, radius)
	ret0, _ := ret[0].([]*models.BarberProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchBarbers indicates an expected call of SearchBarbers.
func (mr *MockStorageInterfaceMockRecorder) SearchBarbers(lat, lng, radius any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBarbers", reflect.TypeOf((*MockStorageInterface)(nil).SearchBarbers), lat, lng, radius)
}

// UpdateAppointment mocks base method.
func (m *MockStorageInterface) UpdateAppointment(appointment *models.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppointment", appointment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAppointment indicates an expected call of UpdateAppointment.
func (mr *MockStorageInterfaceMockRecorder) UpdateAppointment(appointment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppointment", reflect.TypeOf((*MockStorageInterface)(nil).UpdateAppointment), appointment)
}

// UpdateBarberProfile mocks base method.
func (m *MockStorageInterface) UpdateBarberProfile(profile *models.BarberProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBarberProfile", profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBarberProfile indicates an expected call of UpdateBarberProfile.
func (mr *MockStorageInterfaceMockRecorder) UpdateBarberProfile(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBarberProfile", reflect.TypeOf((*MockStorageInterface)(nil).UpdateBarberProfile), profile)
}

// UpdateUser mocks base method.
func (m *MockStorageInterface) UpdateUser(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStorageInterfaceMockRecorder) UpdateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStorageInterface)(nil).UpdateUser), user)
}

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockAuthServiceInterface) GenerateToken(userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthServiceInterfaceMockRecorder) GenerateToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).GenerateToken), userID)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceInterface) RefreshToken(refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshToken), refreshToken)
}

// ValidateToken mocks base method.
func (m *MockAuthServiceInterface) ValidateToken(token string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthServiceInterfaceMockRecorder) ValidateToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).ValidateToken), token)
}

// MockNotificationServiceInterface is a mock of NotificationServiceInterface interface.
type MockNotificationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceInterfaceMockRecorder is the mock recorder for MockNotificationServiceInterface.
type MockNotificationServiceInterfaceMockRecorder struct {
	mock *MockNotificationServiceInterface
}

// NewMockNotificationServiceInterface creates a new mock instance.
func NewMockNotificationServiceInterface(ctrl *gomock.Controller) *MockNotificationServiceInterface {
	mock := &MockNotificationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationServiceInterface) EXPECT() *MockNotificationServiceInterfaceMockRecorder {
	return m.recorder
}

// SendEmailNotification mocks base method.
func (m *MockNotificationServiceInterface) SendEmailNotification(email, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailNotification", email, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailNotification indicates an expected call of SendEmailNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) SendEmailNotification(email, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).SendEmailNotification), email, subject, body)
}

// SendPushNotification mocks base method.
func (m *MockNotificationServiceInterface) SendPushNotification(userID uuid.UUID, title, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPushNotification", userID, title, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPushNotification indicates an expected call of SendPushNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) SendPushNotification(userID, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).SendPushNotification), userID, title, body)
}

// SendSMSNotification mocks base method.
func (m *MockNotificationServiceInterface) SendSMSNotification(phoneNumber, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSMSNotification", phoneNumber, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSMSNotification indicates an expected call of SendSMSNotification.
func (mr *MockNotificationServiceInterfaceMockRecorder) SendSMSNotification(phoneNumber, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSMSNotification", reflect.TypeOf((*MockNotificationServiceInterface)(nil).SendSMSNotification), phoneNumber, message)
}

// MockPaymentServiceInterface is a mock of PaymentServiceInterface interface.
type MockPaymentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceInterfaceMockRecorder is the mock recorder for MockPaymentServiceInterface.
type MockPaymentServiceInterfaceMockRecorder struct {
	mock *MockPaymentServiceInterface
}

// NewMockPaymentServiceInterface creates a new mock instance.
func NewMockPaymentServiceInterface(ctrl *gomock.Controller) *MockPaymentServiceInterface {
	mock := &MockPaymentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceInterface) EXPECT() *MockPaymentServiceInterfaceMockRecorder {
	return m.recorder
}

// ConfirmPayment mocks base method.
func (m *MockPaymentServiceInterface) ConfirmPayment(paymentIntentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", paymentIntentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockPaymentServiceInterfaceMockRecorder) ConfirmPayment(paymentIntentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockPaymentServiceInterface)(nil).ConfirmPayment), paymentIntentID)
}

// CreatePaymentIntent mocks base method.
func (m *MockPaymentServiceInterface) CreatePaymentIntent(amount float64, currency string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentIntent", amount, currency)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentIntent indicates an expected call of CreatePaymentIntent.
func (mr *MockPaymentServiceInterfaceMockRecorder) CreatePaymentIntent(amount, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentIntent", reflect.TypeOf((*MockPaymentServiceInterface)(nil).CreatePaymentIntent), amount, currency)
}

// RefundPayment mocks base method.
func (m *MockPaymentServiceInterface) RefundPayment(paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPayment", paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundPayment indicates an expected call of RefundPayment.
func (mr *MockPaymentServiceInterfaceMockRecorder) RefundPayment(paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPayment", reflect.TypeOf((*MockPaymentServiceInterface)(nil).RefundPayment), paymentID)
}
